### ISSUE TITLE
fioframe.c

### ISSUE THREAD

**Issue by githubmc** [apiriadmin/APIRI#16]
Compilation errors when compile with the kernel 2.6.22.
./fio/src/fiodriver/fioframe.c uses some structures and functions not available in the kernel 2.6.22 linux/time.h.

**Comment by gallagjm** [comment]
Please either submit a patch for older kernel or at least provide the compilation errors reported by gcc.

**Comment by githubmc** [comment]
CC [M]  ./APIRI-master/fio/src/fiodriver/fioframe.o
./APIRI-master/fio/src/fioDriver/fioframe.c: In function 'fioman_ready_frame_51':
./APIRI-master/fio/src/fioDriver/fioframe.c:406: error: request for member 'tv64' in something not a structure or union
./APIRI-master/fio/src/fioDriver/fioframe.c:407: error: request for member 'tv64' in something not a structure or union
./APIRI-master/fio/src/fioDriver/fioframe.c: In function 'fioman_tx_frame_66':
./APIRI-master/fio/src/fioDriver/fioframe.c:913: error: variable 'tm' has initializer but incomplete type
./APIRI-master/fio/src/fioDriver/fioframe.c:913: warning: excess elements in struct initializer
./APIRI-master/fio/src/fioDriver/fioframe.c:913: warning: (near initialization for 'tm')
./APIRI-master/fio/src/fioDriver/fioframe.c:913: error: storage size of 'tm' isn't known
./APIRI-master/fio/src/fioDriver/fioframe.c:920: warning: implicit declaration of function 'time_to_tm'
./APIRI-master/fio/src/fioDriver/fioframe.c:913: warning: unused variable 'tm'
./APIRI-master/fio/src/fioDriver/fioframe.c: In function 'fioman_ready_frame_9':
./APIRI-master/fio/src/fioDriver/fioframe.c:1095: warning: implicit declaration of function 'ktime_sub_ns'
./APIRI-master/fio/src/fioDriver/fioframe.c:1096: error: incompatible type for argument 1 of 'ktime_to_ns'
./APIRI-master/fio/src/fioDriver/fioframe.c:1097: error: request for member 'tv64' in something not a structure or union
./APIRI-master/fio/src/fioDriver/fioframe.c:1098: error: request for member 'tv64' in something not a structure or union
./APIRI-master/fio/src/fioDriver/fioframe.c: In function 'fioman_tx_frame_9':
./APIRI-master/fio/src/fioDriver/fioframe.c:1128: error: variable 'tm' has initializer but incomplete type 
./APIRI-master/fio/src/fioDriver/fioframe.c:1128: warning: excess elements in struct initializer
./APIRI-master/fio/src/fioDriver/fioframe.c:1128: warning: (near initialization for 'tm')
./APIRI-master/fio/src/fioDriver/fioframe.c:1128: error: storage size of 'tm' isn't known
./APIRI-master/fio/src/fioDriver/fioframe.c:1128: warning: unused variable 'tm'
./APIRI-master/fio/src/fioDriver/fioframe.c: In function 'fioman_ready_frame_0':
./APIRI-master/fio/src/fioDriver/fioframe.c:1198: error: incompatible type for argument 1 of 'ktime_to_ns'
./APIRI-master/fio/src/fioDriver/fioframe.c:1201: error: request for member 'tv64' in something not a structure or union
./APIRI-master/fio/src/fioDriver/fioframe.c:1202: error: request for member 'tv64' in something not a structure or union
./APIRI-master/fio/src/fioDriver/fioframe.c: In function 'fioman_ready_frame_1':
./APIRI-master/fio/src/fioDriver/fioframe.c:1344: error: incompatible type for argument 1 of 'ktime_to_ns'
./APIRI-master/fio/src/fioDriver/fioframe.c:1347: error: request for member 'tv64' in something not a structure or union
./APIRI-master/fio/src/fioDriver/fioframe.c:1348: error: request for member 'tv64' in something not a structure or union
./APIRI-master/fio/src/fioDriver/fioframe.c: In function 'fioman_ready_frame_3':
./APIRI-master/fio/src/fioDriver/fioframe.c:1393: error: incompatible type for argument 1 of 'ktime_to_ns'
./APIRI-master/fio/src/fioDriver/fioframe.c:1398: error: request for member 'tv64' in something not a structure or union
./APIRI-master/fio/src/fioDriver/fioframe.c:1399: error: request for member 'tv64' in something not a structure or union
./APIRI-master/fio/src/fioDriver/fioframe.c: In function 'fioman_ready_frame_10_11':
./APIRI-master/fio/src/fioDriver/fioframe.c:1445: error: incompatible type for argument 1 of 'ktime_to_ns'
./APIRI-master/fio/src/fioDriver/fioframe.c:1448: error: request for member 'tv64' in something not a structure or union
./APIRI-master/fio/src/fioDriver/fioframe.c:1449: error: request for member 'tv64' in something not a structure or union
./APIRI-master/fio/src/fioDriver/fioframe.c: In function 'fioman_ready_frame_12_13':
./APIRI-master/fio/src/fioDriver/fioframe.c:1545: error: incompatible type for argument 1 of 'ktime_to_ns'
./APIRI-master/fio/src/fioDriver/fioframe.c:1548: error: request for member 'tv64' in something not a structure or union
./APIRI-master/fio/src/fioDriver/fioframe.c:1549: error: request for member 'tv64' in something not a structure or union
./APIRI-master/fio/src/fioDriver/fioframe.c: In function 'fioman_ready_frame_18':

**Comment by githubmc** [comment]
resolved.
