### ISSUE TITLE
fioman.c

### ISSUE THREAD

**Issue by githubmc** [apiriadmin/APIRI#17]
Compilation errors when compile with the kernel 2.6.22.
./fio/src/fiodriver/fioman.c uses these functions kfifo_to_user(), kfifo_avail() of linux/kfifo.h which are not available in the kernel 2.6.22.

**Comment by githubmc** [comment]
CC [M]  ./APIRI-master/fio/src/fiodriver/fioman.o
./APIRI-master/fio/src/fioDriver/fioman.c: In function 'fioman_reg_fiod':
./APIRI-master/fio/src/fioDriver/fioman.c:1254: warning: passing argument 1 of 'kfifo_alloc' makes integer from pointer without a cast
./APIRI-master/fio/src/fioDriver/fioman.c:1254: warning: passing argument 3 of 'kfifo_alloc' makes pointer from integer without a cast
./APIRI-master/fio/src/fioDriver/fioman.c:1254: warning: assignment makes integer from pointer without a cast
./APIRI-master/fio/src/fioDriver/fioman.c: In function 'fioman_query_fiod':
./APIRI-master/fio/src/fioDriver/fioman.c:1486: warning: unused variable 'p_priv'
./APIRI-master/fio/src/fioDriver/fioman.c: In function 'fioman_query_frame_notify_status':
./APIRI-master/fio/src/fioDriver/fioman.c:3110: warning: unused variable 'p_app_fiod'
./APIRI-master/fio/src/fioDriver/fioman.c:3109: warning: unused variable 'p_priv'
./APIRI-master/fio/src/fioDriver/fioman.c: In function 'fioman_inputs_trans_read':
./APIRI-master/fio/src/fioDriver/fioman.c:3589: warning: implicit declaration of function 'kfifo_to_user'
./APIRI-master/fio/src/fioDriver/fioman.c: In function 'hm_timeout':
./APIRI-master/fio/src/fioDriver/fioman.c:3814: warning: unused variable 'p_priv_old'
./APIRI-master/fio/src/fioDriver/fioman.c:3813: warning: unused variable 'p_priv_next'
./APIRI-master/fio/src/fioDriver/fioman.c:3812: warning: unused variable 'p_priv_elem'
./APIRI-master/fio/src/fioDriver/fioman.c:3811: warning: unused variable 'p_app_next'
./APIRI-master/fio/src/fioDriver/fioman.c: In function 'fioman_hm_heartbeat':
./APIRI-master/fio/src/fioDriver/fioman.c:3931: warning: format '%d' expects type 'int', but argument 3 has type 'long unsigned int'
./APIRI-master/fio/src/fioDriver/fioman.c:3931: warning: format '%d' expects type 'int', but argument 4 has type 'long unsigned int'

**Comment by githubmc** [comment]
resolved.
