### ISSUE TITLE
front_panel.c

### ISSUE THREAD

**Issue by githubmc** [apiriadmin/APIRI#15]
./fpu/FrontPanelSystem/FrontPanelDriver/front_panel.c

Definitions in device.h has changed a lot since the 2.6 kernel. 
There are compilation errors on these lines when compile with the kernel 2.6.22.

 211 static char *fp_devnode(struct device *dev, mode_t *mode)
 212 {
 213    return kasprintf(GFP_KERNEL, "%s", dev_name(dev));
 214 }

 267 fp_class->devnode = fp_devnode;
 269         for (i = 0; i < ARRAY_SIZE(devlist); i++) {
 270             device_create(fp_class, NULL, MKDEV(fp_major, devlist[i].minor),
 271                  NULL, devlist[i].name );
 273         }

1148 void send_signal( int pid, int sig )
1149 {
1151    struct task_struct * p = pid_task(find_vpid(pid), PIDTYPE_PID);
1152    send_sig_info( sig, SEND_SIG_PRIV, p );
1153 }

**Comment by gallagjm** [comment]
Please either submit a patch for older kernel or at least provide the compilation errors reported by gcc.

**Comment by githubmc** [comment]
[mccain@linuxdev1 FrontPanelDriver]$ make
make -C /home/mccain/ltib-mpc8360epb-20071016/rpm/BUILD/linux-2.6.22 M=/home/mccain/Desktop/tvuong/atcapi/APIRI-master/fpu/FrontPanelSystem/FrontPanelDriver ARCH=powerpc CROSS_COMPILE=/opt/freescale/usr/local/gcc-4.0.2-glibc-2.3.6-nptl-3/powerpc-linux/bin/powerpc-linux- modules
make[1]: Entering directory `/home/mccain/ltib-mpc8360epb-20071016/rpm/BUILD/linux-2.6.22'
  CC [M]  /home/mccain/Desktop/tvuong/atcapi/APIRI-master/fpu/FrontPanelSystem/FrontPanelDriver/front_panel.o
/home/mccain/Desktop/tvuong/atcapi/APIRI-master/fpu/FrontPanelSystem/FrontPanelDriver/front_panel.c: In function 'fp_devnode':
/home/mccain/Desktop/tvuong/atcapi/APIRI-master/fpu/FrontPanelSystem/FrontPanelDriver/front_panel.c:213: warning: implicit declaration of function 'dev_name'
/home/mccain/Desktop/tvuong/atcapi/APIRI-master/fpu/FrontPanelSystem/FrontPanelDriver/front_panel.c:213: warning: format '%s' expects type 'char *', but argument 3 has type 'int'
/home/mccain/Desktop/tvuong/atcapi/APIRI-master/fpu/FrontPanelSystem/FrontPanelDriver/front_panel.c: In function 'fp_init':
/home/mccain/Desktop/tvuong/atcapi/APIRI-master/fpu/FrontPanelSystem/FrontPanelDriver/front_panel.c:267: error: 'struct class' has no member named 'devnode'
/home/mccain/Desktop/tvuong/atcapi/APIRI-master/fpu/FrontPanelSystem/FrontPanelDriver/front_panel.c:271: warning: too many arguments for format
/home/mccain/Desktop/tvuong/atcapi/APIRI-master/fpu/FrontPanelSystem/FrontPanelDriver/front_panel.c: In function 'send_signal':
/home/mccain/Desktop/tvuong/atcapi/APIRI-master/fpu/FrontPanelSystem/FrontPanelDriver/front_panel.c:1149: warning: implicit declaration of function 'find_vpid'
/home/mccain/Desktop/tvuong/atcapi/APIRI-master/fpu/FrontPanelSystem/FrontPanelDriver/front_panel.c:1149: warning: passing argument 1 of 'pid_task' makes pointer from integer without a cast
make[2]: *** [/home/mccain/Desktop/tvuong/atcapi/APIRI-master/fpu/FrontPanelSystem/FrontPanelDriver/front_panel.o] Error 1
make[1]: *** [_module_/home/mccain/Desktop/tvuong/atcapi/APIRI-master/fpu/FrontPanelSystem/FrontPanelDriver] Error 2
make[1]: Leaving directory `/home/mccain/ltib-mpc8360epb-20071016/rpm/BUILD/linux-2.6.22'
make: *** [kernel-module] Error 2
[mccain@linuxdev1 FrontPanelDriver]$

**Comment by githubmc** [comment]
resolved.
